GYM_MANAGEMENT_SYSTEM/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from GYM_MANAGEMENT_SYSTEM.settings import MEDIA_ROOT

from .views import *

urlpatterns = [

    # General 
    path('',HomeView.as_view(),name = ''),   
    path('Faq/',FaqPageView.as_view(),name = 'faq'),      
    path('Enquiry/',EnquiryView.as_view(),name = 'enquiry'),    
    path('pages/<str:page_name>/', StaticPageView.as_view(), name='static_page'),
    path('Gallery/',GalleryView.as_view(),name = 'gallery'),    
    path('Gallery_Photos<pk>/',GalleryPhotosView.as_view(),name = 'gallery_photos'),    
    path('Subscription-Plans/',PricingView.as_view(),name = 'pricing'),    
  
    # User
    path('Login', CustomLoginView.as_view(),name= 'login'), 
    path('Logout', CustomLogoutView.as_view(),name= 'logout'), 
    path('Register', RegisterView.as_view(),name= 'register'), 
    path('Dashboard', DashboardView.as_view(),name= 'dashboard'), 
    path('Edit-Profile', UpdateProfileView.as_view(),name= 'update_profile'), 
    path('Report-To-Trainer', ReportToTrainerView.as_view(),name= 'report_to_trainer'), 

    # User chat
    path('Subscriber-Chat', SubscriberChatView.as_view(),name= 'subscriber_chat'), 
    
    # User Notifications
    path('Notifications', NotificationsView.as_view(),name= 'notifications'), 
    path('Get-Notifications',GetNotificationsView.as_view(),name= 'get_notifications'), 
    path('mark_read_notifications', MarkReadNotificationsView.as_view(),name= 'mark_read_notifications'), 

    # Pricing Plans
    path('Plan_Details/<int:plan_id>', CheckoutView.as_view(),name= 'checkout'), 
    path('Checkout/<int:plan_id>', CheckoutSessionView.as_view(),name= 'checkout_session'), 

    # Stripe Payment
    path('Payment-Successfull', PaymentSuccessfulView.as_view(),name= 'payment_successfull'), 
    path('Payment-Cancel', PaymentCancelView.as_view(),name= 'payment_cancel'), 

    # Trainer
    path('Trainer-Login', TrainerLoginView.as_view(),name= 'trainer_login'), 
    path('Trainer-Dashboard', TrainerDashboardView.as_view(),name= 'trainer_dashboard'), 
    path('Trainer-Logout', TrainerLogoutView.as_view(),name= 'trainer_logout'),
    path('Change-Password', TrainerChangePasswordView.as_view(),name= 'trainer_change_password'),
    path('Account-Settings', TrainerEditProfileView.as_view(),name= 'trainer_edit_profile'),
    path('Assigned-Subscribers', TrainerAssignedSubscribersView.as_view(),name= 'trainer_assigned_subscribers'),
    path('Payments', TrainerPaymentsView.as_view(),name= 'trainer_payments'),
    path('Report-to-user', ReportToUserView.as_view(),name= 'report_to_user'),

    # Trainer notifications
    path('Trainer-Notifications', TrainerNotificationsView.as_view(),name= 'trainer_notifications'),
    path('notifications/mark_all_as_read', MarkAllAsReadView.as_view(),name= 'mark_all_as_read'),

    # Trainer Chat
    path('Trainer-Default-Chat/',TrainerDefaultChatView.as_view(),name = 'trainer_default_chat'),     
    path('Trainer-Chat/<int:subscriber_id>/',TrainerChatView.as_view(),name = 'trainer_chat'),  
    


]+static(settings.MEDIA_URL,document_root = MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
import json

class Banners(models.Model):
    img = models.ImageField(upload_to="banners")
    alt_text = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Banners'

    def __str__(self) -> str:
        return self.alt_text
    
    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))

class Service(models.Model):
    title = models.CharField(max_length=100)
    details = models.TextField(max_length=150)
    img = models.ImageField(upload_to="services")

    def __str__(self) -> str:
        return self.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))


class Faq(models.Model):
    question = models.TextField(max_length=100)
    answer = models.TextField(max_length=100)

    def __str__(self):
        return self.question
    

class Enquiry(models.Model):
    full_name = models.CharField(max_length=100)
    query = models.TextField(max_length=100)
    email = models.CharField(max_length=20)
    send_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name
    
class MainLogo(models.Model):
    logo_image = models.ImageField(upload_to='main_logo/')

    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.logo_image.url))


class Gallery(models.Model):
    title = models.CharField(max_length=50)
    details = models.TextField(max_length=150)
    img = models.ImageField(upload_to="gallery")

    def __str__(self) -> str:
        return self.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))
    
class GalleryImages(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE,null=True)
    alt_text = models.CharField(max_length=50)
    img = models.ImageField(upload_to="gallery_imgs")

    class Meta:
        verbose_name_plural = 'Gallery Images'

    def __str__(self) -> str:
        return self.alt_text
    
    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))


# basic standard ... types of subsciptions 
class  SubscriptionPlans(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    max_members = models.IntegerField(null=True)
    highlight_status = models.BooleanField(default=False,null=True)
    validity = models.IntegerField(null=True)

    class Meta:
        verbose_name_plural = 'Subscription Plans'
    
    def __str__(self) -> str:
        return self.title
    

# Above subscription types features
class SubscriptionPlansFeatures(models.Model):
    subplan = models.ManyToManyField(SubscriptionPlans)
    title = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Subscription Plans Features'
    
    def __str__(self) -> str:
        return self.title
    

# The person to subscribe to a subscription Plan
class Subscriber(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    mobile = models.CharField()
    address = models.TextField(max_length=100)
    img = models.ImageField(upload_to="subs")

    def __str__(self) -> str:
        return  str(self.user)  

    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))


# while doing the subscription
class SubscriptionType(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    plan = models.ForeignKey(SubscriptionPlans, on_delete=models.CASCADE, null=True)
    price = models.IntegerField()
    reg_date = models.DateField(auto_now_add=True,null=True)

    def __str__(self):
        return str(self.user.username)
    

class Trainer(models.Model):
    full_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50,null=True)
    password = models.CharField(max_length=50,null=True)
    mobile = models.IntegerField()
    address = models.TextField()
    is_active = models.BooleanField(default=False)
    details = models.TextField()
    img = models.ImageField(upload_to="trainers")
    social_links = models.JSONField(blank=True,null=True)
    month_salary = models.IntegerField(null=True)
    

    def __str__(self) -> str:
        return self.full_name
    
    def image_tag(self):
        if self.img:
            return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))
        

class TrainerAcheivements(models.Model):
    trainer = models.ForeignKey(Trainer,on_delete=models.CASCADE)
    title = models.CharField(max_length=100) 
    date_awarded = models.DateField()  
    description = models.TextField(max_length=300, blank=True) 
    badge_image = models.ImageField(upload_to='achievement_badges/', blank=True)

    def __str__(self) -> str:
        return self.title
    
    def image_tag(self):
        if self.badge_image:
            return mark_safe('<img src="%s" width ="80"/>' %(self.badge_image.url))


class TrainerSalary(models.Model):
    trainer = models.ForeignKey(Trainer,on_delete=models.CASCADE)
    amount = models.IntegerField()
    deposit_date = models.DateTimeField()
    remarks = models.TextField(blank=True)

    def __str__(self) -> str:
        return str(self.amount)
    
#just giving notification to trainer by admin with websockets
class TrainerNotification(models.Model):
    notif_msg = models.TextField()
    is_read = models.BooleanField(default=False)

    def __str__(self) -> str:
        return str(self.notif_msg)
    
    def save(self, *args, **kwargs):
        super(TrainerNotification, self).save(*args, **kwargs)

        channel_layer = get_channel_layer()
        notif = self.notif_msg
        notif_id = self.pk  # Get the primary key (ID) after saving
        total = TrainerNotification.objects.filter(is_read=False).count()

        async_to_sync(channel_layer.group_send)(
            'noti_group_name',
            {
                'type': 'send_notification',
                'value': json.dumps({
                    'notif_id': notif_id, 
                    'notif': notif,
                    'total': total,
                    'action': 'add' 
                })
            }
        )

    def delete(self, *args, **kwargs):
        notif_id = self.pk
        super(TrainerNotification, self).delete(*args, **kwargs)
        
        channel_layer = get_channel_layer()
        total = TrainerNotification.objects.filter(is_read=False).count()

        async_to_sync(channel_layer.group_send)(
            'noti_group_name',
            {
                'type': 'send_notification',
                'value': json.dumps({
                    'notif_id': notif_id,
                    'total': total,
                    'action': 'delete'
                })
            }
        )

    
# User Notifications and response via ajax
class Notify(models.Model):
    notify_detail = models.TextField()
    read_by_user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    read_by_trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self) ->str:
        return self.notify_detail
    

# Mark as read notifications by user
class NotifUserStatus(models.Model):
    notif = models.ForeignKey(Notify, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Notifications Status'

# Assign a subscriber to the trainer
class AssignSubscriber(models.Model):
    subscriber = models.ForeignKey(SubscriptionType, on_delete=models.CASCADE)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return str(self.subscriber)
    

class TrainerSubscriberReport(models.Model):
    sender_trainer = models.ForeignKey(Trainer, null=True, blank=True, on_delete=models.CASCADE, related_name='reports_sent_as_trainer')
    sender_user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='reports_sent_as_user')
    receiver_trainer = models.ForeignKey(Trainer, null=True, blank=True, on_delete=models.CASCADE, related_name='reports_received_as_trainer')
    receiver_user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='reports_received_as_user')
    report_msg = models.TextField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Trainer/User Reports'

    def __str__(self) -> str:
        if self.sender_trainer:
            sender = self.sender_trainer
        else:
            sender = self.sender_user
        
        if self.receiver_trainer:
            receiver = self.receiver_trainer
        else:
            receiver = self.receiver_user

        return f"Report from {sender} to {receiver}: {self.report_msg[:20]}..."

main/forms.py
from django import forms
from .import models

from django.contrib.auth.forms import AuthenticationForm,UserCreationForm,UserChangeForm,PasswordChangeForm
from django.contrib.auth.models import User 

class EnquiryForms(forms.ModelForm):
    class Meta:
        model = models.Enquiry

        fields = ('full_name','email','query')


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(), required=True)
    password = forms.CharField(widget=forms.PasswordInput(), required=True)


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email','password1', 'password2']


class EditUserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email']


class EditUserPasswordForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']


class TrainerLoginForm(forms.ModelForm):
    class Meta:
        model = models.Trainer
        fields = ['username', 'password']
        widgets = {
            'password': forms.PasswordInput(attrs={'placeholder': 'Password'}),
        }

class EditTrainerProfileForm(UserChangeForm):
    class Meta:
        model = models.Trainer
        fields = ['full_name','mobile','address','details','img']


class EditTrainerPasswordForm(forms.Form):

    old_password = forms.CharField(
        max_length=50,required=True,
        widget=forms.PasswordInput(attrs={})
        )
    
    new_password1 = forms.CharField(
        max_length=50,required=True,
        widget=forms.PasswordInput(attrs={})
        )
    
    new_password2 = forms.CharField(
        max_length=50,required=True,
        widget=forms.PasswordInput(attrs={})
        )
    

class ReportToUserForm(forms.ModelForm):
    class Meta:
        model = models.TrainerSubscriberReport
        fields = ['receiver_user','report_msg','sender_trainer']
        widgets = {'sender_trainer':forms.HiddenInput()}


class ReportToTrainerForm(forms.ModelForm):
    class Meta:
        model = models.TrainerSubscriberReport
        fields = ['receiver_trainer','report_msg']
        widgets = {'sender_user':forms.HiddenInput()}

templates/trainer/assigned_subscribers.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<main>
    <section class="container my-4">
        <div class="row">
            <!-- Left Sidebar -->
            <div class="col-lg-3 col-md-3">
                {% include 'trainer/left_sidebar.html' %}
            </div>

            <!-- Main Content -->
            <div class="col-9">
                <h2 class="text-center mb-4 section-heading border-bottom pb-3">My Subscribers</h2>

                <div class="row">
                    {% for ts in trainer_subscribers %}
                    <div class="col-md-6">
                        <div class="card shadow-sm mb-4">
                            <div class="card-body d-flex align-items-center">
                                <!-- <div class="avatar rounded-circle mr-3" style="width: 50px; height: 50px; background-color: #f0f0f0;">
                                    {{ts.subscriber.user.img.url}}
                                </div> -->
                                <h5 class="mb-0">{{ ts.subscriber|capfirst  }}</h5>
                                <button data-bs-toggle="modal" data-bs-target="#exampleModal" title="Info" class="btn  btn-sm ms-auto fs-5"><i class="bi bi-info-circle"></i></button>

                                <!-- Modal start -->
                                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-md">
                                      <div class="modal-content">
                                        <div class="modal-header">
                                          <h5 class="modal-title ms-auto" id="exampleModalLabel">{{ ts.subscriber|capfirst  }} Details</h5>
                                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>

                                        <div class="modal-body">
                                          <table class="table table-hover">
                                                <thead>
                                                    <tr>
                                                        <th>Plan</th>
                                                        <th>Price</th>
                                                        <th>Registration Date</th>
                                                    </tr>
                                                </thead>

                                                <tbody>
                                                        <tr>
                                                            <td>{{ ts.subscriber.plan }}</td>
                                                            <td>{{ ts.subscriber.price}} $</td>
                                                            <td>{{ ts.subscriber.reg_date }}</td>
                                                        </tr>
                                                </tbody>
                                          </table>
                                        </div>

                                        <div class="modal-footer">
                                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        </div>
                                      </div>
                                    </div>
                                  </div>

                                  <!-- modal end -->
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>
        </div> <!-- End of row -->

    </section>
</main>

{% endblock %}

templates/trainer/change_password.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<main>
    <section class="container my-4">
        <div class="row">

        <div class="col-lg-3 col-md-3">
            {% include 'trainer/left_sidebar.html' %}
        </div>

        <div class="col-lg-9 col-md-9">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-10">
                    <div class="card shadow-lg border-0">
                    <div class="card-body p-5">
                        <h2 class="text-center mb-4 section-heading border-bottom pb-3">Change Password</h2>
                        <form method="post" action="{% url 'trainer_change_password' %}">
                            {% csrf_token %}
                            {{ form.non_field_errors }}

                            <div class="form-group mb-4">
                                <label for="id_old_password" class="form-label">Old Password</label>
                                <div style="display:inline-block; margin-left: 95px;">
                                    {{ password_form.old_password }}
                                </div>
                            </div>

                            <div class="form-group mb-4">
                                <label for="id_new_password1" class="form-label">New Password</label>
                                <div style="display:inline-block; margin-left: 88px;">
                                    {{ password_form.new_password1 }}
                                </div>
                                
                            </div>

                            <div class="form-group mb-4">
                                <label for="id_new_password2" class="form-label">Confirm New Password</label>
                                <div style="display:inline-block; margin-left: 29px;">
                                    {{ password_form.new_password2 }}
                                </div>
                            </div>

                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-warning btn-block">Update</button>
                            </div>
                            
                        </form>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
</main>

{% endblock %}

templates/trainer/edit_profile.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<main>
    <section class="container my-4">
        <div class="row">
            <!-- Left Sidebar -->
            <div class="col-lg-3 col-md-3">
                {% include 'trainer/left_sidebar.html' %}
            </div>

            <!-- Edit Profile Form -->
            <div class="col-lg-9 col-md-9">
                <div class="row justify-content-center">
                    <div class="col-lg-8 col-md-10">
                        <div class="card shadow-lg border-0">
                            <div class="card-body p-5">
                                <h2 class="text-center mb-4 section-heading border-bottom pb-3">Edit Profile</h2>
                                <form method="post" action="{% url 'trainer_edit_profile' %}" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form.non_field_errors }}

                                    <div class="row mb-4">
                                        <label for="id_full_name" class="col-sm-4 col-form-label">Full Name</label>
                                        <div class="col-sm-8">
                                            {{ form.full_name }}
                                        </div>
                                    </div>

                                    <div class="row mb-4">
                                        <label for="id_mobile" class="col-sm-4 col-form-label">Mobile No.</label>
                                        <div class="col-sm-8">
                                            {{ form.mobile }}
                                        </div>
                                    </div>

                                    <div class="row mb-4">
                                        <label for="id_address" class="col-sm-4 col-form-label">Address</label>
                                        <div class="col-sm-8">
                                            {{ form.address }}
                                        </div>
                                    </div>

                                    <div class="row mb-4">
                                        <label for="id_details" class="col-sm-4 col-form-label">Details</label>
                                        <div class="col-sm-8">
                                            {{ form.details }}
                                        </div>
                                    </div>

                                    <div class="row mb-4">
                                        <label for="id_img" class="col-sm-4 col-form-label">Image</label>
                                        <div class="col-sm-8">
                                            {% if form.instance.img %}
                                                <img src="{{ form.instance.img.url }}" alt="Trainer Image" style="max-width: 150px; max-height: 150px;">
                                            {% endif %}
                                            <input type="file" name="img" id="id_img" class="form-control mt-2">
                                        </div>
                                    </div>

                                    <div class="d-grid gap-2">
                                        <button type="submit" class="btn btn-warning btn-block">Update</button>
                                    </div>

                                    <!-- <br> Don't want to update anything? <a href="{% url 'trainer_dashboard' %}" class="text-decoration-none">Go Back</a> -->
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- End of col-lg-9 -->
        </div> <!-- End of row -->
    </section>
</main>

{% endblock %}

templates/trainer/left_sidebar.html
<style>
    .list-group {
        margin-top: 0; /* Ensure consistent margin */
    }
    .left-sidebar {
        position: sticky;
        top: 0;
    }
    .list-group-item {
        display: flex;
        align-items: center;
        gap: 10px;
    }
    .list-group-item i {
        font-size: 1.5rem; /* Icon size */
    }
    .name-label {
        font-weight: bold;
        font-size: 1.2rem;
        color: #007bff;
        text-align: center;
        border: 2px solid #007bff;
        border-radius: 5px;
        padding: 5px;
        text-transform: capitalize;
    }
</style>


<div class="list-group">
    <a href="{% url 'trainer_dashboard' %}" class="list-group-item {% if request.path == '/Trainer-Dashboard' %} active {% endif %}">
        <i class="bi bi-house"></i> Dashboard
    </a>
    <a href="{% url 'trainer_assigned_subscribers'%}" class="list-group-item {% if request.path == '/Assigned-Subscribers' %} active {% endif %}">
        <i class="bi bi-people"></i> My Subscribers
    </a>
    <a href="{% url 'trainer_payments' %}" class="list-group-item {% if request.path == '/Payments' %} active {% endif %}">
        <i class="bi bi-cash"></i> Payments
    </a>

    <a href="{% url 'trainer_default_chat' %}" class="list-group-item {% if '/Trainer-Chat/' in request.path %} active {% endif %}">
        <i class="bi bi-chat-dots"></i> Chat 
        <!-- <span class="float-end badge bg-info mt-1 ms-auto">123</span>    -->
    </a>
    
    <a href="{% url 'trainer_notifications' %}" class="list-group-item {% if request.path == '/Trainer-Notifications' %} active {% endif %}">
        <i class="bi bi-bell"></i> Notifications 
        <span class="float-end badge bg-info mt-1 ms-auto">{{unread_count}}</span>
    </a>
    <a href="{% url 'trainer_change_password' %}" class="list-group-item {% if request.path == '/Change-Password' %} active {% endif %}">
        <i class="bi bi-lock"></i> Change Password
    </a>
    <a href="{% url 'report_to_user' %}" class="list-group-item {% if request.path == '/Report-to-user' %} active {% endif %}">
        <i class="bi bi-flag"></i> Report to Users
    </a>
    <a href="{% url 'trainer_edit_profile' %}" class="list-group-item {% if request.path == '/Account-Settings' %} active {% endif %}">
        <i class="bi bi-gear"></i> Settings
    </a>
</div>

templates/trainer/login.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<main>
    <section class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <div class="card shadow-lg border-0">
                    <div class="card-body p-5">
                        <h2 class="text-center mb-4 section-heading border-bottom pb-3 ">Trainer Login</h2>
                        <form method="post" action="{% url 'trainer_login' %}">
                            {% csrf_token %}
                            {{ form.non_field_errors }}

                            <div class="form-group mb-4">
                                
                                {{ form.username|as_crispy_field }}
                                <div class="form-text text-muted">

                                </div>
                                {{ form.username.errors }}
                            </div>

                            <div class="form-group mb-4" >
                                
                                {{ form.password|as_crispy_field }}
                                <div class="form-text text-muted" >

                                </div>
                                {{ form.password.errors }}
                            </div>

                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-warning btn-block">Login</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}

templates/trainer/report_to_user.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<main>
    <section class="container my-4">
        <div class="row">

        <div class="col-lg-3 col-md-3">
            {% include 'trainer/left_sidebar.html' %}
        </div>

        <div class="col-lg-9 col-md-9">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-10">
                    <div class="card shadow-lg border-0">
                    <div class="card-body p-5">
                        <h2 class="text-center mb-4 section-heading border-bottom pb-3">Report To User</h2>
                        
                        <form method="post" action="{% url 'report_to_user' %}">
                            {% csrf_token %}
                            {{ form.non_field_errors }}

                            <div class="form-group mb-4">
                                <label for="id_old_password" class="form-label ">Select User</label>
                                <div style="display:inline-block; margin-left: 95px;">
                                    {{ form.receiver_user }}
                                </div>
                            </div>

                            <div class="form-group mb-4">
                                <label for="id_new_password1" class="form-label col-form-label col-sm-4">Report Message</label>
                                <div class="col-sm-8">
                                    {{ form.report_msg }}
                                </div>
                                
                            </div>

                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-warning btn-block">Submit</button>
                            </div>
                            
                        </form>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
</main>

{% endblock %}