GYM_MANAGEMENT_SYSTEM/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from GYM_MANAGEMENT_SYSTEM.settings import MEDIA_ROOT

from .views import *

urlpatterns = [

    # General 
    path('',HomeView.as_view(),name = ''),   
    path('Faq/',FaqPageView.as_view(),name = 'faq'),      
    path('Enquiry/',EnquiryView.as_view(),name = 'enquiry'),    
    path('pages/<str:page_name>/', StaticPageView.as_view(), name='static_page'),
    path('Gallery/',GalleryView.as_view(),name = 'gallery'),    
    path('Gallery_Photos<pk>/',GalleryPhotosView.as_view(),name = 'gallery_photos'),    
    path('Subscription-Plans/',PricingView.as_view(),name = 'pricing'),    
  
    # User
    path('Login', CustomLoginView.as_view(),name= 'login'), 
    path('Logout', CustomLogoutView.as_view(),name= 'logout'), 
    path('Register', RegisterView.as_view(),name= 'register'), 
    path('Dashboard', DashboardView.as_view(),name= 'dashboard'), 
    path('Edit-Profile', UpdateProfileView.as_view(),name= 'update_profile'), 
    path('Report-To-Trainer', ReportToTrainerView.as_view(),name= 'report_to_trainer'), 

    # User chat
    path('Subscriber-Chat', SubscriberChatView.as_view(),name= 'subscriber_chat'), 
    
    # User Notifications
    path('Notifications', NotificationsView.as_view(),name= 'notifications'), 
    path('Get-Notifications',GetNotificationsView.as_view(),name= 'get_notifications'), 
    path('mark_read_notifications', MarkReadNotificationsView.as_view(),name= 'mark_read_notifications'), 

    # Pricing Plans
    path('Plan_Details/<int:plan_id>', CheckoutView.as_view(),name= 'checkout'), 
    path('Checkout/<int:plan_id>', CheckoutSessionView.as_view(),name= 'checkout_session'), 

    # Stripe Payment
    path('Payment-Successfull', PaymentSuccessfulView.as_view(),name= 'payment_successfull'), 
    path('Payment-Cancel', PaymentCancelView.as_view(),name= 'payment_cancel'), 

    # Trainer
    path('Trainer-Login', TrainerLoginView.as_view(),name= 'trainer_login'), 
    path('Trainer-Dashboard', TrainerDashboardView.as_view(),name= 'trainer_dashboard'), 
    path('Trainer-Logout', TrainerLogoutView.as_view(),name= 'trainer_logout'),
    path('Change-Password', TrainerChangePasswordView.as_view(),name= 'trainer_change_password'),
    path('Account-Settings', TrainerEditProfileView.as_view(),name= 'trainer_edit_profile'),
    path('Assigned-Subscribers', TrainerAssignedSubscribersView.as_view(),name= 'trainer_assigned_subscribers'),
    path('Payments', TrainerPaymentsView.as_view(),name= 'trainer_payments'),
    path('Report-to-user', ReportToUserView.as_view(),name= 'report_to_user'),

    # Trainer notifications
    path('Trainer-Notifications', TrainerNotificationsView.as_view(),name= 'trainer_notifications'),
    path('notifications/mark_all_as_read', MarkAllAsReadView.as_view(),name= 'mark_all_as_read'),

    # Trainer Chat
    path('Trainer-Default-Chat/',TrainerDefaultChatView.as_view(),name = 'trainer_default_chat'),     
    path('Trainer-Chat/<int:subscriber_id>/',TrainerChatView.as_view(),name = 'trainer_chat'),  
    


]+static(settings.MEDIA_URL,document_root = MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
import json

class Banners(models.Model):
    img = models.ImageField(upload_to="banners")
    alt_text = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Banners'

    def __str__(self) -> str:
        return self.alt_text
    
    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))

class Service(models.Model):
    title = models.CharField(max_length=100)
    details = models.TextField(max_length=150)
    img = models.ImageField(upload_to="services")

    def __str__(self) -> str:
        return self.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))


class Faq(models.Model):
    question = models.TextField(max_length=100)
    answer = models.TextField(max_length=100)

    def __str__(self):
        return self.question
    

class Enquiry(models.Model):
    full_name = models.CharField(max_length=100)
    query = models.TextField(max_length=100)
    email = models.CharField(max_length=20)
    send_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name
    
class MainLogo(models.Model):
    logo_image = models.ImageField(upload_to='main_logo/')

    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.logo_image.url))


class Gallery(models.Model):
    title = models.CharField(max_length=50)
    details = models.TextField(max_length=150)
    img = models.ImageField(upload_to="gallery")

    def __str__(self) -> str:
        return self.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))
    
class GalleryImages(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE,null=True)
    alt_text = models.CharField(max_length=50)
    img = models.ImageField(upload_to="gallery_imgs")

    class Meta:
        verbose_name_plural = 'Gallery Images'

    def __str__(self) -> str:
        return self.alt_text
    
    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))


# basic standard ... types of subsciptions 
class  SubscriptionPlans(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    max_members = models.IntegerField(null=True)
    highlight_status = models.BooleanField(default=False,null=True)
    validity = models.IntegerField(null=True)

    class Meta:
        verbose_name_plural = 'Subscription Plans'
    
    def __str__(self) -> str:
        return self.title
    

# Above subscription types features
class SubscriptionPlansFeatures(models.Model):
    subplan = models.ManyToManyField(SubscriptionPlans)
    title = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Subscription Plans Features'
    
    def __str__(self) -> str:
        return self.title
    

# The person to subscribe to a subscription Plan
class Subscriber(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    mobile = models.CharField()
    address = models.TextField(max_length=100)
    img = models.ImageField(upload_to="subs")

    def __str__(self) -> str:
        return  str(self.user)  

    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))


# while doing the subscription
class SubscriptionType(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    plan = models.ForeignKey(SubscriptionPlans, on_delete=models.CASCADE, null=True)
    price = models.IntegerField()
    reg_date = models.DateField(auto_now_add=True,null=True)

    def __str__(self):
        return str(self.user.username)
    

class Trainer(models.Model):
    full_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50,null=True)
    password = models.CharField(max_length=50,null=True)
    mobile = models.IntegerField()
    address = models.TextField()
    is_active = models.BooleanField(default=False)
    details = models.TextField()
    img = models.ImageField(upload_to="trainers")
    social_links = models.JSONField(blank=True,null=True)
    month_salary = models.IntegerField(null=True)
    

    def __str__(self) -> str:
        return self.full_name
    
    def image_tag(self):
        if self.img:
            return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))
        

class TrainerAcheivements(models.Model):
    trainer = models.ForeignKey(Trainer,on_delete=models.CASCADE)
    title = models.CharField(max_length=100) 
    date_awarded = models.DateField()  
    description = models.TextField(max_length=300, blank=True) 
    badge_image = models.ImageField(upload_to='achievement_badges/', blank=True)

    def __str__(self) -> str:
        return self.title
    
    def image_tag(self):
        if self.badge_image:
            return mark_safe('<img src="%s" width ="80"/>' %(self.badge_image.url))


class TrainerSalary(models.Model):
    trainer = models.ForeignKey(Trainer,on_delete=models.CASCADE)
    amount = models.IntegerField()
    deposit_date = models.DateTimeField()
    remarks = models.TextField(blank=True)

    def __str__(self) -> str:
        return str(self.amount)
    
#just giving notification to trainer by admin with websockets
class TrainerNotification(models.Model):
    notif_msg = models.TextField()
    is_read = models.BooleanField(default=False)

    def __str__(self) -> str:
        return str(self.notif_msg)
    
    def save(self, *args, **kwargs):
        super(TrainerNotification, self).save(*args, **kwargs)

        channel_layer = get_channel_layer()
        notif = self.notif_msg
        notif_id = self.pk  # Get the primary key (ID) after saving
        total = TrainerNotification.objects.filter(is_read=False).count()

        async_to_sync(channel_layer.group_send)(
            'noti_group_name',
            {
                'type': 'send_notification',
                'value': json.dumps({
                    'notif_id': notif_id, 
                    'notif': notif,
                    'total': total,
                    'action': 'add' 
                })
            }
        )

    def delete(self, *args, **kwargs):
        notif_id = self.pk
        super(TrainerNotification, self).delete(*args, **kwargs)
        
        channel_layer = get_channel_layer()
        total = TrainerNotification.objects.filter(is_read=False).count()

        async_to_sync(channel_layer.group_send)(
            'noti_group_name',
            {
                'type': 'send_notification',
                'value': json.dumps({
                    'notif_id': notif_id,
                    'total': total,
                    'action': 'delete'
                })
            }
        )

    
# User Notifications and response via ajax
class Notify(models.Model):
    notify_detail = models.TextField()
    read_by_user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    read_by_trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self) ->str:
        return self.notify_detail
    

# Mark as read notifications by user
class NotifUserStatus(models.Model):
    notif = models.ForeignKey(Notify, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Notifications Status'

# Assign a subscriber to the trainer
class AssignSubscriber(models.Model):
    subscriber = models.ForeignKey(SubscriptionType, on_delete=models.CASCADE)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return str(self.subscriber)
    

class TrainerSubscriberReport(models.Model):
    sender_trainer = models.ForeignKey(Trainer, null=True, blank=True, on_delete=models.CASCADE, related_name='reports_sent_as_trainer')
    sender_user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='reports_sent_as_user')
    receiver_trainer = models.ForeignKey(Trainer, null=True, blank=True, on_delete=models.CASCADE, related_name='reports_received_as_trainer')
    receiver_user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='reports_received_as_user')
    report_msg = models.TextField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Trainer/User Reports'

    def __str__(self) -> str:
        if self.sender_trainer:
            sender = self.sender_trainer
        else:
            sender = self.sender_user
        
        if self.receiver_trainer:
            receiver = self.receiver_trainer
        else:
            receiver = self.receiver_user

        return f"Report from {sender} to {receiver}: {self.report_msg[:20]}..."

templates/cancel.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>
    <section class="container my-4">
        <!-- Cancel Message -->
        <h3 class="text-center mb-4 section-heading border-bottom pb-2 text-danger">Oops! Your payment was cancelled</h3>

        <!-- Encouraging Message -->
        <p class="text-center mb-4">It looks like something went wrong with your payment. Don't worry, you can try again or choose a different plan!</p>

        <!-- Action Buttons -->
        <div class="text-center">
            <a href="{% url 'pricing' %}" class="btn btn-secondary mb-2">View Pricing Plans</a>
            <a href="{% url 'dashboard' %}" class="btn btn-primary mb-2">Go to Dashboard</a>
        </div>
    </section>
</main>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% block content %}
<style>
   .table th, .table td {
    width: 25%; /* Adjust this based on your table layout */
    text-align: center;
}
</style>
<main>
    <!-- Services -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">Checkout</h1>
            <table class="table table-bordered">
                <thead class="table-warning">
                    <tr>
                        <th>Plan</th>
                        <th>Plan Detail</th>
                        <th>Payment For</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <table class="table-bordered table">
                                <tr>
                                    <th>Name</th>
                                    <td>{{plan_details.title}}</td>
                                </tr>
                                <tr>
                                    <th>Price</th>
                                    <td>{{plan_details.price}} $</td>
                                </tr>
                                <tr>
                                    <th>Maximum Members</th>
                                    <td>{{plan_details.max_members}}</td>
                                </tr>
                                <tr>
                                    <th>Already Registered</th>
                                    <td>15</td>
                                </tr>
                                <tr>
                                    <th>Remaining Slots</th>
                                    <td>15</td>
                                </tr>
                            </table>
                        </td>
                        <td>
                            <ul class="list-unstyled">
                                {% for feature in plan_details.subscriptionplansfeatures_set.all %}
                              <li>{{feature.title}}</li>
                              {% endfor %}
                            </ul>
                        </td>
                        <td>
                            <table class="table table-bordered">
                                <tr>
                                    <td><input data-planprice="{{plan_details.price}}" data-discount="0" type="radio" id="validity1" name="validity" class="select-validity" value="1" checked/></td>
                                    <th><label for="validity1">1 Month</label></th>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td><input data-planprice="{{plan_details.price}}" data-discount="10" type="radio" id="validity2" name="validity" class="select-validity" value="3" /></td>
                                    <th><label for="validity2">3 Month</label></th>
                                    <td>10% Off</td>
                                </tr>
                                <tr>
                                    <td><input data-planprice="{{plan_details.price}}" data-discount="20" type="radio" id="validity3" value="6" name="validity" class="select-validity" /></td>
                                    <th><label for="validity3">6 Month</label></th>
                                    <td>20% Off</td>
                                </tr>
                                <tr>
                                    <td><input data-planprice="{{plan_details.price}}" data-discount="30" type="radio" id="validity4" value="12" name="validity" class="select-validity" /></td>
                                    <th><label for="validity4">12 Month</label></th>
                                    <td>30% Off</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </tbody>
                <tfoot class="table-info">
                    <tr>
                        <td></td>
                        <th>Total Amount</th>
                        <td>
                            <b>
                                <span class="originalLabel" style="font-size: smaller;">Original:</span>
                                <span class="originalAmount" style="text-decoration: line-through; margin-right: 10px;">${{plan_details.price}}</span> 

                                <span class="discountedLabel" style="font-size: smaller;">Discounted:</span>
                                $<span class="totalAmount">{{plan_details.price}}</span>
                            </b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2"></td>

                        <td>
                            <form method="post" action="{% url 'checkout_session' plan_details.id %}">
                                {% csrf_token %}
                                <input type="submit" value="Proceed to Payment" class="btn btn-primary" />
                            </form>    
                        </td>
                    </tr>
                </tfoot>
            </table>
    </section>
</main>
<!-- End -->

<script type="text/javascript">
$(document).ready(function(){
    function updatePricing() {
        var _planPrice = parseFloat($(".select-validity:checked").attr('data-planprice')); // Original price
        var _planDisc = parseFloat($(".select-validity:checked").attr('data-discount'));   // Discount percentage
        var _planValid = parseInt($(".select-validity:checked").val());                    // Number of months

        var _totalPrice = _planPrice * _planValid;  // Original total price

        var _discountedPrice = _totalPrice;
        if(_planDisc > 0){
            _discountedPrice = _totalPrice - (_totalPrice * _planDisc / 100);  // Calculating the discounted price
            $(".originalAmount").show(); // Show the original price with strikethrough
            $(".discountedLabel").show(); // Show the discounted label
        } else {
            _discountedPrice = _totalPrice;
            $(".originalAmount").hide(); // Hide the original price with strikethrough for 1-month plan
            $(".discountedLabel").hide(); // Hide the discounted label for 1-month plan
        }

        // Update the HTML with both original and discounted prices
        $(".originalAmount").text('$' + _totalPrice.toFixed(2));   // Show original price with a strikethrough
        $(".totalAmount").text(_discountedPrice.toFixed(2));       // Show discounted price
    }

    // Initialize the state based on the selected radio button
    $(".select-validity:checked").each(updatePricing);
    
    // Update pricing on radio button change
    $(".select-validity").on('click', updatePricing);
});

</script>

{% endblock %}

templates/contact_us.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
    <!-- Contact Us Section -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">Contact Us</h1>

        <div class="row">
            <!-- Map on the Left -->
            <div class="col-md-6">
                <div style="overflow:hidden;max-width:100%;width:100%;height:400px;">
                    <div id="gmap-canvas" style="height:100%; width:100%;max-width:100%;">
                        <iframe style="height:100%;width:100%;border:0;" frameborder="0" 
                                src="https://www.google.com/maps/embed/v1/place?q=pakistan&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"
                                allowfullscreen></iframe>
                    </div>
                </div>
            </div>

            <!-- Static Contact Information on the Right -->
            <div class="col-md-6">
                <h4 class="mb-3 text-center">Information</h4>
                <div class="card shadow-lg p-3">
                    <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th scope="row">Email</th>
                                <td>example@email.com</td>
                            </tr>
                            <tr>
                                <th scope="row">Website</th>
                                <td><a href="https://www.example.com" target="_blank">www.example.com</a></td>
                            </tr>
                            <tr>
                                <th scope="row">Phone Number</th>
                                <td>+92 123 456 7890</td>
                            </tr>
                            <tr>
                                <th scope="row">Address</th>
                                <td>123 Gym Street, Fitness City, Pakistan</td>
                            </tr>
                            <tr>
                                <th scope="row">Social Media</th>
                                <td>
                                    <a href="#" target="_blank">Facebook</a>, 
                                    <a href="#" target="_blank">Instagram</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

templates/gallery.html
{% extends 'base.html' %}
{% block content %}


<style>

.card {
    display: flex;
    flex-direction: column;
    align-items: center; /* Center align the card contents */
}

.card-img-top {
    height: 200px; /* Set a fixed height */
    object-fit: cover; /* Maintain aspect ratio */
    width: 100%; /* Ensure the image takes full width of the card */
}

.card-body {
    display: flex;
    flex-direction: column;
    align-items: center; /* Center align the content in the card body */
}

.btn-info {
    background-color: #17a2b8; /* Customize as needed */
    border: none;
    margin-top: auto; /* Push the button to the bottom */
}

.btn-info:hover {
    background-color: #138496; /* Customize as needed */
    transition: background-color 0.3s ease;
}
</style>
<main>
  <!-- Services -->
  <section class="container my-4">
      <h1 class="text-center mb-4 section-heading border-bottom pb-2">Gallery</h1>
      <div class="row">
        {% for gallerys in gallery %}
          <div class="col-md-4 mb-4">
              <div class="card shadow">
                <img src="{{ gallerys.img.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">{{ gallerys.title }}</h5>
                  <p class="card-text">{{ gallerys.details }}</p>
                  <a href="{% url 'gallery_photos' gallerys.id %}" class="btn btn-info text-white">View All</a>
                </div>
              </div>
          </div>
        {% endfor %}
      </div>
  </section>
  <!-- End -->
</main>


{% endblock %}

templates/pricing.html
{% extends 'base.html' %}
{% load static %}
{% load purchased_package %}
{% block content %}
{% load mathfilters %}

<style>
    .card {
      height: 100%;
      box-shadow: 0 8px 30px rgba(0, 0, 0, 0.2);
      transition: transform 0.2s;
    }

    .card:hover {
      transform: translateY(-5px);
    }
</style>

<section class="container my-4">
  <h1 class="text-center mb-4 section-heading border-bottom pb-2">Subscription Plans</h1>
  <main>
      <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
          {% for pricings in pricing %}
          <div class="col">
              <div class="card mb-4 rounded-3 shadow {% if pricings.highlight_status %} border-primary {% endif %}">
                  {% if pricings.highlight_status %}
                  <div class="card-header py-3 text-white bg-primary border-primary">
                      <h4 class="my-0 fw-normal">{{ pricings.title }}</h4>
                  </div>
                  {% else %}
                  <div class="card-header py-3">
                      <h4 class="my-0 fw-normal">{{ pricings.title }}</h4>
                  </div>
                  {% endif %}
                  <div class="card-body d-flex flex-column">
                    <h1 class="card-title pricing-card-title">${{ pricings.price }} 
                        <small class="text-muted fw-light"> / {{ pricings.validity }} days</small>
                    </h1>
                    <p class="text-success">Maximum capacity: <b>{{ pricings.max_members|sub:pricings.registered_members }}</b></p>
                    <ul class="list-unstyled mt-3 mb-4">
                        {% for features in pricings.subscriptionplansfeatures_set.all %}
                        <li><strong><b>.</b></strong> {{ features.title }}</li>
                        {% endfor %}
                    </ul>
                    <div class="mt-auto">
                        
                        {% if user.is_authenticated %}
                            {% check_purchased_package request.user.id as has_purchased_any_plan %}
                            {% check_purchased_package request.user.id pricings.id as checkpackage %}

                            {% if checkpackage %}
                                {% if is_expired %}
                                    <!-- Allow renewing the expired plan -->
                                    <a href="{% url 'checkout' pricings.id %}" class="w-100 btn btn-lg btn-outline-primary">Get Started</a>
                                {% else %}
                                    <!-- If plan is active, show purchased button -->
                                    <a href="#" class="w-100 btn btn-lg btn-dark disabled">Purchased</a>
                                {% endif %}
                            {% elif has_purchased_any_plan %}
                                {% if is_expired %}
                                    <!-- If any plan is expired, allow purchasing new plan -->
                                    <a href="{% url 'checkout' pricings.id %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
                                {% else %}
                                    <!-- Disable other plans if there's an active plan -->
                                    <a href="#" class="w-100 btn btn-lg btn-outline-secondary disabled">Unavailable</a>
                                {% endif %}
                            {% else %}
                                <!-- If no plan is purchased, allow purchasing -->
                                <a href="{% url 'checkout' pricings.id %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
              </div>
          </div>
          {% endfor %}
      </div>
  </main>
</section>

{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<main>
    <section class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <div class="card shadow-lg border-0">
                    <div class="card-body p-5">
                        <h2 class="text-center mb-4 section-heading border-bottom pb-3">Register</h2>
                        <form method="post" action="{% url 'register' %}">
                            {% csrf_token %}
                            {{ form.non_field_errors }}

                            <div class="form-group mb-4">
                                <label for="id_username" class="form-label">Username &nbsp; &nbsp;&nbsp;</label>
                                {{ form.username }}
                                <div class="form-text text-muted">
                                    {{ form.username.help_text }}
                                </div>
                                {{ form.username.errors }}
                            </div>

                            <div class="form-group mb-4">
                                <label for="id_email" class="form-label">Email &nbsp; &nbsp;&nbsp;</label>
                                    <div style="display:inline-block; margin-left: 32px;">
                                        {{ form.email }}
                                    </div>
                                <div class="form-text text-muted">
                                    {{ form.email.help_text }}
                                </div>
                                {{ form.email.errors }}
                            </div>

                            <div class="form-group mb-4">
                                <label for="id_password1" class="form-label">Password &nbsp; &nbsp;&nbsp;&nbsp;</label>
                                {{ form.password1 }}
                                <div class="form-text text-muted">
                                    {{ form.password1.help_text }}
                                </div>
                                {{ form.password1.errors }}
                            </div>

                            <div class="form-group mb-4">
                                <label for="id_password2" class="form-label">Confirm Password &nbsp;</label>
                                {{ form.password2 }}
                                <div class="form-text text-muted">
                                    Enter the same password as before, for verification.
                                </div>
                                {{ form.password2.errors }}
                            </div>

                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-warning btn-block">Register</button>
                            </div>

                            <br> Already have an account? <a href ="{% url 'login' %}" class ="text-decoration-none">Login here</a>
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}