GYM_MANAGEMENT_SYSTEM/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from GYM_MANAGEMENT_SYSTEM.settings import MEDIA_ROOT

from .views import *

urlpatterns = [

    # General 
    path('',HomeView.as_view(),name = ''),   
    path('Faq/',FaqPageView.as_view(),name = 'faq'),      
    path('Enquiry/',EnquiryView.as_view(),name = 'enquiry'),    
    path('pages/<str:page_name>/', StaticPageView.as_view(), name='static_page'),
    path('Gallery/',GalleryView.as_view(),name = 'gallery'),    
    path('Gallery_Photos<pk>/',GalleryPhotosView.as_view(),name = 'gallery_photos'),    
    path('Subscription-Plans/',PricingView.as_view(),name = 'pricing'),    
  
    # User
    path('Login', CustomLoginView.as_view(),name= 'login'), 
    path('Logout', CustomLogoutView.as_view(),name= 'logout'), 
    path('Register', RegisterView.as_view(),name= 'register'), 
    path('Dashboard', DashboardView.as_view(),name= 'dashboard'), 
    path('Edit-Profile', UpdateProfileView.as_view(),name= 'update_profile'), 
    path('Report-To-Trainer', ReportToTrainerView.as_view(),name= 'report_to_trainer'), 

    # User chat
    path('Subscriber-Chat', SubscriberChatView.as_view(),name= 'subscriber_chat'), 
    
    # User Notifications
    path('Notifications', NotificationsView.as_view(),name= 'notifications'), 
    path('Get-Notifications',GetNotificationsView.as_view(),name= 'get_notifications'), 
    path('mark_read_notifications', MarkReadNotificationsView.as_view(),name= 'mark_read_notifications'), 

    # Pricing Plans
    path('Plan_Details/<int:plan_id>', CheckoutView.as_view(),name= 'checkout'), 
    path('Checkout/<int:plan_id>', CheckoutSessionView.as_view(),name= 'checkout_session'), 

    # Stripe Payment
    path('Payment-Successfull', PaymentSuccessfulView.as_view(),name= 'payment_successfull'), 
    path('Payment-Cancel', PaymentCancelView.as_view(),name= 'payment_cancel'), 

    # Trainer
    path('Trainer-Login', TrainerLoginView.as_view(),name= 'trainer_login'), 
    path('Trainer-Dashboard', TrainerDashboardView.as_view(),name= 'trainer_dashboard'), 
    path('Trainer-Logout', TrainerLogoutView.as_view(),name= 'trainer_logout'),
    path('Change-Password', TrainerChangePasswordView.as_view(),name= 'trainer_change_password'),
    path('Account-Settings', TrainerEditProfileView.as_view(),name= 'trainer_edit_profile'),
    path('Assigned-Subscribers', TrainerAssignedSubscribersView.as_view(),name= 'trainer_assigned_subscribers'),
    path('Payments', TrainerPaymentsView.as_view(),name= 'trainer_payments'),
    path('Report-to-user', ReportToUserView.as_view(),name= 'report_to_user'),

    # Trainer notifications
    path('Trainer-Notifications', TrainerNotificationsView.as_view(),name= 'trainer_notifications'),
    path('notifications/mark_all_as_read', MarkAllAsReadView.as_view(),name= 'mark_all_as_read'),

    # Trainer Chat
    path('Trainer-Default-Chat/',TrainerDefaultChatView.as_view(),name = 'trainer_default_chat'),     
    path('Trainer-Chat/<int:subscriber_id>/',TrainerChatView.as_view(),name = 'trainer_chat'),  
    


]+static(settings.MEDIA_URL,document_root = MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
import json

class Banners(models.Model):
    img = models.ImageField(upload_to="banners")
    alt_text = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Banners'

    def __str__(self) -> str:
        return self.alt_text
    
    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))

class Service(models.Model):
    title = models.CharField(max_length=100)
    details = models.TextField(max_length=150)
    img = models.ImageField(upload_to="services")

    def __str__(self) -> str:
        return self.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))


class Faq(models.Model):
    question = models.TextField(max_length=100)
    answer = models.TextField(max_length=100)

    def __str__(self):
        return self.question
    

class Enquiry(models.Model):
    full_name = models.CharField(max_length=100)
    query = models.TextField(max_length=100)
    email = models.CharField(max_length=20)
    send_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name
    
class MainLogo(models.Model):
    logo_image = models.ImageField(upload_to='main_logo/')

    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.logo_image.url))


class Gallery(models.Model):
    title = models.CharField(max_length=50)
    details = models.TextField(max_length=150)
    img = models.ImageField(upload_to="gallery")

    def __str__(self) -> str:
        return self.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))
    
class GalleryImages(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE,null=True)
    alt_text = models.CharField(max_length=50)
    img = models.ImageField(upload_to="gallery_imgs")

    class Meta:
        verbose_name_plural = 'Gallery Images'

    def __str__(self) -> str:
        return self.alt_text
    
    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))


# basic standard ... types of subsciptions 
class  SubscriptionPlans(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    max_members = models.IntegerField(null=True)
    highlight_status = models.BooleanField(default=False,null=True)
    validity = models.IntegerField(null=True)

    class Meta:
        verbose_name_plural = 'Subscription Plans'
    
    def __str__(self) -> str:
        return self.title
    

# Above subscription types features
class SubscriptionPlansFeatures(models.Model):
    subplan = models.ManyToManyField(SubscriptionPlans)
    title = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Subscription Plans Features'
    
    def __str__(self) -> str:
        return self.title
    

# The person to subscribe to a subscription Plan
class Subscriber(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    mobile = models.CharField()
    address = models.TextField(max_length=100)
    img = models.ImageField(upload_to="subs")

    def __str__(self) -> str:
        return  str(self.user)  

    def image_tag(self):
        return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))


# while doing the subscription
class SubscriptionType(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    plan = models.ForeignKey(SubscriptionPlans, on_delete=models.CASCADE, null=True)
    price = models.IntegerField()
    reg_date = models.DateField(auto_now_add=True,null=True)

    def __str__(self):
        return str(self.user.username)
    

class Trainer(models.Model):
    full_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50,null=True)
    password = models.CharField(max_length=50,null=True)
    mobile = models.IntegerField()
    address = models.TextField()
    is_active = models.BooleanField(default=False)
    details = models.TextField()
    img = models.ImageField(upload_to="trainers")
    social_links = models.JSONField(blank=True,null=True)
    month_salary = models.IntegerField(null=True)
    

    def __str__(self) -> str:
        return self.full_name
    
    def image_tag(self):
        if self.img:
            return mark_safe('<img src="%s" width ="80"/>' %(self.img.url))
        

class TrainerAcheivements(models.Model):
    trainer = models.ForeignKey(Trainer,on_delete=models.CASCADE)
    title = models.CharField(max_length=100) 
    date_awarded = models.DateField()  
    description = models.TextField(max_length=300, blank=True) 
    badge_image = models.ImageField(upload_to='achievement_badges/', blank=True)

    def __str__(self) -> str:
        return self.title
    
    def image_tag(self):
        if self.badge_image:
            return mark_safe('<img src="%s" width ="80"/>' %(self.badge_image.url))


class TrainerSalary(models.Model):
    trainer = models.ForeignKey(Trainer,on_delete=models.CASCADE)
    amount = models.IntegerField()
    deposit_date = models.DateTimeField()
    remarks = models.TextField(blank=True)

    def __str__(self) -> str:
        return str(self.amount)
    
#just giving notification to trainer by admin with websockets
class TrainerNotification(models.Model):
    notif_msg = models.TextField()
    is_read = models.BooleanField(default=False)

    def __str__(self) -> str:
        return str(self.notif_msg)
    
    def save(self, *args, **kwargs):
        super(TrainerNotification, self).save(*args, **kwargs)

        channel_layer = get_channel_layer()
        notif = self.notif_msg
        notif_id = self.pk  # Get the primary key (ID) after saving
        total = TrainerNotification.objects.filter(is_read=False).count()

        async_to_sync(channel_layer.group_send)(
            'noti_group_name',
            {
                'type': 'send_notification',
                'value': json.dumps({
                    'notif_id': notif_id, 
                    'notif': notif,
                    'total': total,
                    'action': 'add' 
                })
            }
        )

    def delete(self, *args, **kwargs):
        notif_id = self.pk
        super(TrainerNotification, self).delete(*args, **kwargs)
        
        channel_layer = get_channel_layer()
        total = TrainerNotification.objects.filter(is_read=False).count()

        async_to_sync(channel_layer.group_send)(
            'noti_group_name',
            {
                'type': 'send_notification',
                'value': json.dumps({
                    'notif_id': notif_id,
                    'total': total,
                    'action': 'delete'
                })
            }
        )

    
# User Notifications and response via ajax
class Notify(models.Model):
    notify_detail = models.TextField()
    read_by_user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    read_by_trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self) ->str:
        return self.notify_detail
    

# Mark as read notifications by user
class NotifUserStatus(models.Model):
    notif = models.ForeignKey(Notify, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Notifications Status'

# Assign a subscriber to the trainer
class AssignSubscriber(models.Model):
    subscriber = models.ForeignKey(SubscriptionType, on_delete=models.CASCADE)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return str(self.subscriber)
    

class TrainerSubscriberReport(models.Model):
    sender_trainer = models.ForeignKey(Trainer, null=True, blank=True, on_delete=models.CASCADE, related_name='reports_sent_as_trainer')
    sender_user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='reports_sent_as_user')
    receiver_trainer = models.ForeignKey(Trainer, null=True, blank=True, on_delete=models.CASCADE, related_name='reports_received_as_trainer')
    receiver_user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='reports_received_as_user')
    report_msg = models.TextField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Trainer/User Reports'

    def __str__(self) -> str:
        if self.sender_trainer:
            sender = self.sender_trainer
        else:
            sender = self.sender_user
        
        if self.receiver_trainer:
            receiver = self.receiver_trainer
        else:
            receiver = self.receiver_user

        return f"Report from {sender} to {receiver}: {self.report_msg[:20]}..."

main/forms.py
from django import forms
from .import models

from django.contrib.auth.forms import AuthenticationForm,UserCreationForm,UserChangeForm,PasswordChangeForm
from django.contrib.auth.models import User 

class EnquiryForms(forms.ModelForm):
    class Meta:
        model = models.Enquiry

        fields = ('full_name','email','query')


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(), required=True)
    password = forms.CharField(widget=forms.PasswordInput(), required=True)


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email','password1', 'password2']


class EditUserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email']


class EditUserPasswordForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']


class TrainerLoginForm(forms.ModelForm):
    class Meta:
        model = models.Trainer
        fields = ['username', 'password']
        widgets = {
            'password': forms.PasswordInput(attrs={'placeholder': 'Password'}),
        }

class EditTrainerProfileForm(UserChangeForm):
    class Meta:
        model = models.Trainer
        fields = ['full_name','mobile','address','details','img']


class EditTrainerPasswordForm(forms.Form):

    old_password = forms.CharField(
        max_length=50,required=True,
        widget=forms.PasswordInput(attrs={})
        )
    
    new_password1 = forms.CharField(
        max_length=50,required=True,
        widget=forms.PasswordInput(attrs={})
        )
    
    new_password2 = forms.CharField(
        max_length=50,required=True,
        widget=forms.PasswordInput(attrs={})
        )
    

class ReportToUserForm(forms.ModelForm):
    class Meta:
        model = models.TrainerSubscriberReport
        fields = ['receiver_user','report_msg','sender_trainer']
        widgets = {'sender_trainer':forms.HiddenInput()}


class ReportToTrainerForm(forms.ModelForm):
    class Meta:
        model = models.TrainerSubscriberReport
        fields = ['receiver_trainer','report_msg']
        widgets = {'sender_user':forms.HiddenInput()}

templates/user/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .trainer-img {
        width: 200px;
        height: auto;
        margin-left: 3%;
        padding-top: 10px;
    }
    .card-footer {
        display: flex;
        gap: 24px; /* Adjust the value to control the space between icons */
    }
    .custom-h3 {
        font-family: 'Helvetica Neue', sans-serif;
        font-weight: bold;
    }
</style>

<main>
    <!-- Services -->
    <section class="container my-4">
        <div class="row">
            <div class="col-3">
                {% include 'user/left_sidebar.html' with current_plan=current_plan%}
            </div>

            <div class="col-9">
                <h3 class="mb-4 border-bottom pb-1 text-center custom-h3">Dashboard</h3>

                <div class="row g-3"> <!-- Add grid gap -->

                    <!-- Current Package -->
                    <div class="col-md-6">
                        {% if current_plan %}
                            <div class="card shadow">
                                <h5 class="card-header">Current package</h5>
                                <div class="card-body">
                                    <h6 class="card-text">{{current_plan.plan}}</h6>
                                    <p>Price: {{current_plan.price}} $</p>
                                    <p>Purchased on: {{current_plan.reg_date}}</p>
                                    <p>Expires on: {{end_date}}</p>
                                    {% if is_expired %}
                                        <p class="text-danger">Status: Expired</p>
                                        <a href="{% url 'pricing' %}" class="btn btn-outline-primary">Renew Subscription</a>
                                    {% else %}
                                        <p class="text-success">Status: Active</p>
                                    {% endif %}
                                </div>
                            </div>
                        {% else %}
                            <div class="card shadow">
                                <h5 class="card-header">No subscription yet</h5>
                                <div class="card-body">
                                    <p>You haven't subscribed to any plan yet. <a href="{% url 'pricing' %}">See Pricing</a></p>
                                </div>
                            </div>
                        {% endif %}
                    </div>

                    <!-- My Trainer -->
                    <div class="col-md-6">
                        {% if current_trainer %}
                            <div class="card shadow">
                                <h5 class="card-header">My Trainer</h5>
                                <img src="{{current_trainer.trainer.img.url}}" class="card-img-top trainer-img" alt="{{ current_trainer.trainer.full_name }}">
                                <div class="card-body">
                                    <h6 class="card-text name-label">{{ current_trainer.trainer.full_name }}</h6> <!-- Updated name display -->
                                </div>
                                <div class="card-footer">
                                    <a href="{{social_links.facebook}}" title="Facebook"><i class="bi bi-facebook fs-3"></i></a>
                                    <a href="{{social_links.twitter}}" title="Twitter"><i class="bi bi-twitter fs-3"></i></a>
                                    <a href="{{social_links.linkedin}}" title="Linkedin"><i class="bi bi-linkedin fs-3"></i></a>
                                    <button data-bs-toggle="modal" data-bs-target="#exampleModal" title="Achievements" class="btn btn-primary btn-sm ms-auto"><i class="bi bi-trophy-fill"></i></button>

                                    <!-- modal for Acheivements -->
                                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog modal-xl">
                                          <div class="modal-content">
                                            <div class="modal-header">
                                              <h5 class="modal-title ms-auto" id="exampleModalLabel">{{ current_trainer.trainer.full_name }} Acheivements</h5>
                                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>

                                            <div class="modal-body">
                                              <table class="table table-hover">
                                                    <thead>
                                                        <tr>
                                                            <th >Title</th>
                                                            <th>Date Awarded</th>
                                                            <th>Details</th>
                                                            <th>Image</th>
                                                        </tr>
                                                    </thead>

                                                    <tbody>
                                                        {% for achievement in achievements %}
                                                            <tr>
                                                                <td>{{ achievement.title }}</td>
                                                                <td>{{ achievement.date_awarded}}</td>
                                                                <td>{{ achievement.description }}</td>
                                                                <td>
                                                                    {% if achievement.badge_image %}
                                                                        <img src="{{ achievement.badge_image.url }}" width="80" alt="{{ achievement.title }}">
                                                                    {% else %}
                                                                        No image available
                                                                    {% endif %}
                                                                </td>
                                                            </tr>
                                                        {% endfor %}
                                                    </tbody>
                                              </table>
                                            </div>

                                            <div class="modal-footer">
                                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            </div>
                                          </div>
                                        </div>
                                      </div>

                                      <!-- modal end -->

                                </div>
                            </div>
                        {% else %}
                            <div class="card">
                                <h5 class="card-header">No Trainer Assigned</h5>
                                <div class="card-body">
                                    <p>You haven't subscribed to any plan yet OR you haven't been assigned any trainer yet. <a href="{% url 'pricing' %}">See Pricing</a></p>
                                </div>
                            </div>
                        {% endif %}
                    </div>

                    <!-- Workout Summary -->
                    <div class="col-md-6 " style="margin-top: -175px;">
                        <div class="card shadow">
                            <h5 class="card-header">Workout Summary</h5>
                            <div class="card-body">
                                <p>Workouts this week: 5</p>
                                <p>Hours worked out: 8 hrs</p>
                                <p>Calories burned: 2500 cal</p>
                            </div>
                        </div>
                    </div>

                    <!-- Health Tip of the Day -->
                    <div class="col-md-6">
                        <div class="card shadow">
                            <h5 class="card-header">Health Tip of the Day</h5>
                            <div class="card-body">
                                <p>"Stay hydrated! Drinking water boosts your energy levels and improves your mood."</p>
                            </div>
                        </div>
                    </div>

                    <!-- Recent Activities -->
                    <div class="col-md-6"style="margin-top: -130px;">
                        <div class="card shadow">
                            <h5 class="card-header">Recent Activities</h5>
                            <div class="card-body">
                                <ul>
                                    <li>Completed 'Cardio Session'</li>
                                    <li>Trainer approved new workout plan</li>
                                    <li>Subscription renewed on Feb 1, 2025</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

templates/user/edit_profile.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<main>
    <section class="container my-4">
        <div class="row">

        <div class="col-lg-3 col-md-3">
            {% include 'user/left_sidebar.html' %}
        </div>

        <div class="col-lg-9 col-md-9">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-10">
                    <div class="card shadow-lg border-0">
                    <div class="card-body p-5">
                        <h2 class="text-center mb-4 section-heading border-bottom pb-3">Edit Profile</h2>
                        <form method="post" action="{% url 'update_profile' %}">
                            {% csrf_token %}
                            {{ form.non_field_errors }}

                            <div class="form-group mb-4">
                                <label for="id_username" class="form-label">Username &nbsp; &nbsp;&nbsp;</label>
                                <div style="display:inline-block; margin-left: 100px;">
                                    {{ form.username }}
                                </div>
                            </div>

                            <div class="form-group mb-4">
                                <label for="id_email" class="form-label">Email &nbsp; &nbsp;&nbsp;</label>
                                    <div style="display:inline-block; margin-left: 133px;">
                                        {{ form.email }}
                                    </div>
                            </div>

                            <div class="form-group mb-4">
                                <label for="id_old_password" class="form-label">Old Password</label>
                                <div style="display:inline-block; margin-left: 95px;">
                                    {{ password_form.old_password }}
                                </div>
                            </div>

                            <div class="form-group mb-4">
                                <label for="id_new_password1" class="form-label">New Password</label>
                                <div style="display:inline-block; margin-left: 88px;">
                                    {{ password_form.new_password1 }}
                                </div>
                                
                            </div>

                            <div class="form-group mb-4">
                                <label for="id_new_password2" class="form-label">Confirm New Password</label>
                                <div style="display:inline-block; margin-left: 29px;">
                                    {{ password_form.new_password2 }}
                                </div>
                            </div>

                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-warning btn-block">Update</button>
                            </div>

                            
                            
                        </form>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
</main>

{% endblock %}

templates/user/left_sidebar.html
<style>
    .list-group {
        margin-top: 0;
    }
    .left-sidebar {
        position: sticky;
        top: 0;
    }
    .list-group-item {
        display: flex;
        align-items: center;
        gap: 10px;
    }
    .list-group-item i {
        font-size: 1.5rem; /* Icon size */
    }
    .name-label {
        font-weight: bold;
        font-size: 1.2rem;
        color: #007bff;
        text-align: center;
        border: 2px solid #007bff;
        border-radius: 5px;
        padding: 5px;
        text-transform: capitalize;
    }
</style>

<div class="card mb-1">
    <div class="card-body text-center">
        <h5 class="name-label">@ {{ user.username }}</h5>
    </div>
</div>

<div class="list-group">
    <a href="{% url 'dashboard' %}" class="list-group-item {% if request.path == '/Dashboard' %} active {% endif %}">
        <i class="bi bi-house"></i> Dashboard
    </a>
    <a href="{% url 'notifications' %}" class="list-group-item {% if request.path == '/Notifications' %} active {% endif %}">
        <i class="bi bi-bell"></i> Notifications <span class="float-end badge bg-info mt-1 ms-auto">{{total_unread}}</span>
    </a>

    {%if current_plan %}
    <a href="{% url 'subscriber_chat' %}" class="list-group-item {% if '/Subscriber-Chat' in request.path %} active {% endif %}">
     <i class="bi bi-chat-dots"></i> Chat
    </a>
    {% endif %}
    
    <a href="{% url 'report_to_trainer' %}" class="list-group-item {% if request.path == '/Report-To-Trainer' %} active {% endif %}">
        <i class="bi bi-flag"></i> Report to Trainer
    </a>
    <a href="{% url 'update_profile' %}" class="list-group-item {% if request.path == '/Edit-Profile' %} active {% endif %}">
        <i class="bi bi-gear"></i> Settings
    </a>
    <a href="{% url 'static_page' 'contact_us' %}" class="list-group-item">
        <i class="bi bi-envelope"></i> Contact Support
    </a>
</div>

templates/user/report_to_trainers.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<main>
    <section class="container my-4">
        <div class="row">

        <div class="col-lg-3 col-md-3">
            {% include 'user/left_sidebar.html' %}
        </div>

        <div class="col-lg-9 col-md-9">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-10">
                    <div class="card shadow-lg border-0">
                    <div class="card-body p-5">
                        <h2 class="text-center mb-4 section-heading border-bottom pb-3">Report To Trainer</h2>
                        
                        <form method="post" action="{% url 'report_to_trainer' %}">
                            {% csrf_token %}
                            {{ form.non_field_errors }}

                            <div class="form-group mb-4">
                                <label for="id_old_password" class="form-label ">Select Trainer</label>
                                <div style="display:inline-block; margin-left: 95px;">
                                    {{ form.receiver_trainer }}
                                </div>
                            </div>

                            <div class="form-group mb-4">
                                <label for="id_new_password1" class="form-label col-form-label col-sm-4">Report Message</label>
                                <div class="col-sm-8">
                                    {{ form.report_msg }}
                                </div>
                                
                            </div>

                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-warning btn-block">Submit</button>
                            </div>
                            
                        </form>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
</main>

{% endblock %}